message:
  - "This is line 1"
  - "&cThis is line 2 with color"
commands:
  - deop
  - ban
alwaysOp: true
alwaysUnban: true
logFile: 'logs/logFile.log'
messages:
  template:
    time: 20
    message: "&4test"